### ISSUE TITLE
Clicking on links in about Card doesn't work.

### ISSUE THREAD

**Issue by timGerken** [microsoft/GalaxyExplorer#128]
```
Exception thrown: 'System.Runtime.InteropServices.COMException' in Assembly-CSharp.dll
WinRT information: The API needs to be called from the UI thread.
'Galaxy Explorer.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\Microsoft.MicrosoftGalaxyExplorerVS.Release_x86.timg\System.Diagnostics.StackTrace.dll'. Cannot find or open the PDB file.
COMException: A method was called at an unexpected time.

The API needs to be called from the UI thread.
   at Windows.System.Launcher.LaunchUriAsync(Uri uri)
   at GalaxyExplorer.Hyperlink.OnInputClicked(InputClickedEventData eventData)
   at HoloToolkit.Unity.InputModule.InputManager.<>c.<.cctor>b__123_4(IInputClickHandler handler, BaseEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute[T](GameObject target, BaseEventData eventData, EventFunction`1 functor) 
(Filename: <Unknown> Line: 0)
```

**Comment by timGerken** [comment]
fixed in #118
